name: myapp
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/Calculator.png
    - assets/Profile_Picture.png
    - assets/news.png
    - assets/budget.png
    - assets/simulation.png
    - assets/forum.png
    - assets/data_analysis.png
    - assets/news1.png
    - assets/news2.png
    - assets/news3.png
    - assets/news4.png
    - assets/news5.png


